SalaryConversion/Controllers/SalaryConversionController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SalaryConversion.Models;
using SalaryConversion.Models.SalaryConversion;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SalaryConversion.Controllers
{

    [Route("salary-conversion")]
    public class SalaryConversionController : Controller
    {
        private readonly ISalaryConversion _Interface;
        private readonly ILogger<SalaryConversionController> _Logger;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public SalaryConversionController(ILogger<SalaryConversionController> logger, ISalaryConversion intface, IWebHostEnvironment hostingEnvironment)
        {
            _Interface = intface;
            _Logger = logger;
            _hostingEnvironment = hostingEnvironment;
        }

        [Route("index")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("get-datasource")]
        public async Task<IActionResult> GetDataSourceAsync(DataTableBindingModel Args)
        {
            var salaryFile = Path.Combine(Directory.GetCurrentDirectory(), _hostingEnvironment.WebRootPath, "sourcefile/salary_data.json");
            string JSON = System.IO.File.ReadAllText(salaryFile);
          
            return Json(await _Interface.GetDataSalaryAsync(Args, JSON));
        }
    }
}

SalaryConversion/Controllers/SensorAggregationController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SalaryConversion.Models;
using SalaryConversion.Models.SensorAggregation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SalaryConversion.Controllers
{
    [Route("sensor-aggregation")]
    public class SensorAggregationController : Controller
    {
        private readonly ISensorAggregation _Interface;
        private readonly ILogger<SensorAggregationController> _Logger;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public SensorAggregationController(ILogger<SensorAggregationController> logger, ISensorAggregation intface, IWebHostEnvironment hostingEnvironment)
        {
            _Interface = intface;
            _Logger = logger;
            _hostingEnvironment = hostingEnvironment;
        }
        [Route("index")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost("get-datasource")]
        public IActionResult GetDataSourceAsync(DataTableBindingModel Args)
        {
            var sensorFile = Path.Combine(Directory.GetCurrentDirectory(), _hostingEnvironment.WebRootPath, "sourcefile/sensor_data.json");
            string JSON = System.IO.File.ReadAllText(sensorFile);

            return Json(_Interface.GetDataSensor(Args, JSON));
        }
    }
}

SalaryConversion/Views/Shared/_HeaderScripts.cshtml
<script type="text/javascript" src="~/js/libraries/jquery.min.js?ver=1.0.0"></script>
<script type="text/javascript" src="~/js/libraries/jquery.dataTables.min.js?ver=1.0.0"></script>
<script type="text/javascript" src="~/js/libraries/jquery.validate.min.js?ver=1.0.0"></script>

@*<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>*@

<!--Import jQuery before export.js-->
<!--<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>-->
<!--Data Table-->
<!--<script type="text/javascript" src=" https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>-->

SalaryConversion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CAD-IT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/components.css" />
    <link rel="stylesheet" href="~/css/core.css" />
    @await Html.PartialAsync("_HeaderScripts")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CAD-IT Test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalaryConversion" asp-action="Index">Salary Conversion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SensorAggregation" asp-action="Index">Sensor Aggregation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CAD-IT Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>